# Generated by Django 6.1 on 2026-08-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='uploads/')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone number'), ('email', 'Email address')], max_length=10)),
                ('contact_column', models.CharField(blank=True, max_length=255)),
                ('default_region', models.CharField(blank=True, max_length=2)),
                ('country_column', models.CharField(blank=True, max_length=255)),
                ('columns', models.JSONField(default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('combine_rule', models.CharField(default='all', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=60)),
                ('error', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('service_key', models.CharField(max_length=40)),
                ('service_label', models.CharField(max_length=60)),
                ('task_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_task_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('checked', models.IntegerField(default=0)),
                ('valid', models.IntegerField(default=0)),
                ('invalid', models.IntegerField(default=0)),
                ('unresolved', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='verifier.verificationjob')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=320)),
                ('normalized', models.CharField(blank=True, max_length=320)),
                ('is_eligible', models.BooleanField(default=True)),
                ('flag_reason', models.CharField(blank=True, max_length=120)),
                ('final_outcome', models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unresolved', 'Unresolved'), ('skipped', 'Skipped')], max_length=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='verifier.verificationjob')),
            ],
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unresolved', 'Unresolved'), ('skipped', 'Skipped')], max_length=12)),
                ('raw_status', models.CharField(blank=True, max_length=60)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='verifier.contact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='verifier.jobstep')),
            ],
            options={
                'indexes': [models.Index(fields=['step', 'outcome'], name='verifier_st_step_id_62589b_idx')],
                'unique_together': {('step', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('data', models.JSONField()),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rows', to='verifier.contact')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='verifier.verificationjob')),
            ],
            options={
                'ordering': ['row_index'],
                'indexes': [models.Index(fields=['job', 'row_index'], name='verifier_so_job_id_7fc9f2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['job', 'normalized'], name='verifier_co_job_id_742c01_idx'),
        ),
    ]
