# Generated by Django 6.1 on 2026-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstep',
            name='checker',
            field=models.CharField(default='basic', max_length=40),
        ),
        migrations.AddField(
            model_name='jobstep',
            name='checker_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
