# Generated by Django 6.1 on 2026-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_jobstep_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepresult',
            name='raw_status',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='verificationjob',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Phone number'), ('email', 'Email address'), ('username', 'Username')], max_length=10),
        ),
    ]
